### Live server test
GET http://localhost:8000


# ======== Admin registration and login
### Admin user registration
POST http://localhost:8000/api/v1/register-login
Content-Type: application/json 

{
    "fName": "Prateek",
    "lName": "Khindri",
    "dob": "2020-02-19",
    "phone": "0444444444",
    "email": "a@a.com",
    "password": "123456",
    "address": "somewhere in sydney"
}


### Admin user registration
PATCH http://localhost:8000/api/v1/register-login
Content-Type: application/json 

{
    "email" : "a@gmail.com",
    "verificationCode": "7094a4b1-27e2-4f2e-811b-8e8d07cb612f"
}

### Admin Login
POST http://localhost:8000/api/v1/register-login/login 
Content-Type: application/json 

{
    "email": "a@gmail.com", 
    "password": "123456"
}


# ============ Category API

### fetch categories
GET http://localhost:8000/api/v1/categories/

### Post Category
POST http://localhost:8000/api/v1/categories/
Content-Type: application/json 

{
    "status": "inactive",
    "name": "Sneakerskk",
    "parentCatId": null

}


### Update Category
PUT http://localhost:8000/api/v1/categories/
Content-Type: application/json 

{
    "_id": "62c8b7136abfc597a4b81555",
    "status": "active",
    "name": "Mobile Phones",
    "parentCatId": null

}